fix(417): Make vsock-addr and unix-socket conflict
Closes #417

Providing both `--vsock-addr` and `--unix-socket` now throws an error:

```console
$ oha --vsock-addr '1:3000' --unix-socket ./socket 'http://localhost:3000'`
error: the argument '--vsock-addr <VSOCK_ADDR>' cannot be used with '--unix-socket <UNIX_SOCKET>'

Usage: oha [FLAGS] [OPTIONS] <url>

For more information, try '--help'.
```